import type { Quiz } from "@/types/quiz"

export const quizData: Quiz[] = [
  // Physics Quizzes
  {
    id: "physics-easy-1",
    title: "Basic Motion and Forces",
    subject: "physics",
    difficulty: "easy",
    timeLimit: 15,
    passingScore: 70,
    totalPoints: 100,
    description: "Introduction to motion, velocity, and basic forces",
    questions: [
      {
        id: "p1q1",
        question: "What is the SI unit of force?",
        options: ["Newton", "Joule", "Watt", "Pascal"],
        correctAnswer: 0,
        explanation: "The Newton (N) is the SI unit of force, named after Sir Isaac Newton.",
        difficulty: "easy",
        subject: "physics",
        topic: "Forces",
        points: 20,
      },
      {
        id: "p1q2",
        question: "If an object moves 10 meters in 2 seconds, what is its average speed?",
        options: ["5 m/s", "10 m/s", "20 m/s", "2 m/s"],
        correctAnswer: 0,
        explanation: "Speed = Distance/Time = 10m/2s = 5 m/s",
        difficulty: "easy",
        subject: "physics",
        topic: "Motion",
        points: 20,
      },
      {
        id: "p1q3",
        question: "What happens to an object at rest according to Newton's first law?",
        options: ["It accelerates", "It stays at rest", "It moves backward", "It vibrates"],
        correctAnswer: 1,
        explanation:
          "Newton's first law states that an object at rest stays at rest unless acted upon by an external force.",
        difficulty: "easy",
        subject: "physics",
        topic: "Newton's Laws",
        points: 20,
      },
      {
        id: "p1q4",
        question: "What is acceleration?",
        options: ["Change in position", "Change in velocity", "Change in mass", "Change in force"],
        correctAnswer: 1,
        explanation: "Acceleration is the rate of change of velocity with respect to time.",
        difficulty: "easy",
        subject: "physics",
        topic: "Motion",
        points: 20,
      },
      {
        id: "p1q5",
        question: "Which of these is a vector quantity?",
        options: ["Speed", "Mass", "Velocity", "Temperature"],
        correctAnswer: 2,
        explanation: "Velocity is a vector quantity because it has both magnitude and direction.",
        difficulty: "easy",
        subject: "physics",
        topic: "Vectors",
        points: 20,
      },
    ],
  },
  {
    id: "physics-medium-1",
    title: "Energy and Work",
    subject: "physics",
    difficulty: "medium",
    timeLimit: 20,
    passingScore: 75,
    totalPoints: 150,
    description: "Understanding work, energy, and power concepts",
    questions: [
      {
        id: "p2q1",
        question: "If a 5kg object is lifted 2 meters high, what is the potential energy gained? (g = 10 m/s²)",
        options: ["50 J", "100 J", "25 J", "200 J"],
        correctAnswer: 1,
        explanation: "PE = mgh = 5kg × 10m/s² × 2m = 100 J",
        difficulty: "medium",
        subject: "physics",
        topic: "Energy",
        points: 30,
      },
      {
        id: "p2q2",
        question: "What is the kinetic energy of a 2kg object moving at 4 m/s?",
        options: ["8 J", "16 J", "32 J", "4 J"],
        correctAnswer: 1,
        explanation: "KE = ½mv² = ½ × 2kg × (4m/s)² = 16 J",
        difficulty: "medium",
        subject: "physics",
        topic: "Energy",
        points: 30,
      },
      {
        id: "p2q3",
        question: "If 100 J of work is done in 5 seconds, what is the power?",
        options: ["20 W", "500 W", "100 W", "5 W"],
        correctAnswer: 0,
        explanation: "Power = Work/Time = 100J/5s = 20 W",
        difficulty: "medium",
        subject: "physics",
        topic: "Power",
        points: 30,
      },
      {
        id: "p2q4",
        question: "According to the work-energy theorem, work done equals:",
        options: ["Change in potential energy", "Change in kinetic energy", "Total energy", "Force times distance"],
        correctAnswer: 1,
        explanation: "The work-energy theorem states that work done equals the change in kinetic energy.",
        difficulty: "medium",
        subject: "physics",
        topic: "Work-Energy Theorem",
        points: 30,
      },
      {
        id: "p2q5",
        question: "What type of energy does a compressed spring have?",
        options: ["Kinetic energy", "Thermal energy", "Elastic potential energy", "Chemical energy"],
        correctAnswer: 2,
        explanation: "A compressed spring stores elastic potential energy.",
        difficulty: "medium",
        subject: "physics",
        topic: "Energy",
        points: 30,
      },
    ],
  },
  {
    id: "physics-hard-1",
    title: "Waves and Oscillations",
    subject: "physics",
    difficulty: "hard",
    timeLimit: 25,
    passingScore: 80,
    totalPoints: 200,
    description: "Advanced concepts in wave motion and simple harmonic motion",
    questions: [
      {
        id: "p3q1",
        question: "A wave has frequency 50 Hz and wavelength 2 m. What is its speed?",
        options: ["25 m/s", "100 m/s", "50 m/s", "200 m/s"],
        correctAnswer: 1,
        explanation: "Wave speed = frequency × wavelength = 50 Hz × 2 m = 100 m/s",
        difficulty: "hard",
        subject: "physics",
        topic: "Waves",
        points: 40,
      },
      {
        id: "p3q2",
        question: "In simple harmonic motion, when is the acceleration maximum?",
        options: ["At equilibrium", "At maximum displacement", "At half displacement", "Acceleration is constant"],
        correctAnswer: 1,
        explanation: "In SHM, acceleration is maximum at maximum displacement where a = -ω²x is greatest.",
        difficulty: "hard",
        subject: "physics",
        topic: "Simple Harmonic Motion",
        points: 40,
      },
      {
        id: "p3q3",
        question: "What happens when two waves of equal amplitude and frequency interfere constructively?",
        options: ["They cancel out", "Amplitude doubles", "Frequency doubles", "Wavelength doubles"],
        correctAnswer: 1,
        explanation: "Constructive interference occurs when waves are in phase, resulting in doubled amplitude.",
        difficulty: "hard",
        subject: "physics",
        topic: "Wave Interference",
        points: 40,
      },
      {
        id: "p3q4",
        question: "The period of a simple pendulum depends on:",
        options: ["Mass and length", "Length and gravity", "Mass and gravity", "Amplitude and mass"],
        correctAnswer: 1,
        explanation: "T = 2π√(L/g), so period depends only on length and gravitational acceleration.",
        difficulty: "hard",
        subject: "physics",
        topic: "Pendulum",
        points: 40,
      },
      {
        id: "p3q5",
        question: "What is the phase difference between displacement and velocity in SHM?",
        options: ["0°", "90°", "180°", "270°"],
        correctAnswer: 1,
        explanation: "In SHM, velocity leads displacement by 90° (π/2 radians).",
        difficulty: "hard",
        subject: "physics",
        topic: "Simple Harmonic Motion",
        points: 40,
      },
    ],
  },
  {
    id: "physics-medium-2",
    title: "Electricity and Magnetism",
    subject: "physics",
    difficulty: "medium",
    timeLimit: 20,
    passingScore: 75,
    totalPoints: 150,
    description: "Basic concepts of electric circuits and magnetic fields",
    questions: [
      {
        id: "p4q1",
        question: "What is the resistance of a conductor with voltage 12V and current 3A?",
        options: ["4 Ω", "36 Ω", "9 Ω", "15 Ω"],
        correctAnswer: 0,
        explanation: "Using Ohm's law: R = V/I = 12V/3A = 4 Ω",
        difficulty: "medium",
        subject: "physics",
        topic: "Ohm's Law",
        points: 30,
      },
      {
        id: "p4q2",
        question: "In a parallel circuit, what happens to total resistance?",
        options: ["Increases", "Decreases", "Stays same", "Becomes zero"],
        correctAnswer: 1,
        explanation: "In parallel circuits, total resistance is less than the smallest individual resistance.",
        difficulty: "medium",
        subject: "physics",
        topic: "Circuits",
        points: 30,
      },
      {
        id: "p4q3",
        question: "What creates a magnetic field around a wire?",
        options: ["Voltage", "Electric current", "Resistance", "Capacitance"],
        correctAnswer: 1,
        explanation: "Electric current flowing through a wire creates a magnetic field around it.",
        difficulty: "medium",
        subject: "physics",
        topic: "Magnetism",
        points: 30,
      },
      {
        id: "p4q4",
        question: "The unit of electric charge is:",
        options: ["Ampere", "Coulomb", "Volt", "Ohm"],
        correctAnswer: 1,
        explanation: "The Coulomb (C) is the SI unit of electric charge.",
        difficulty: "medium",
        subject: "physics",
        topic: "Electric Charge",
        points: 30,
      },
      {
        id: "p4q5",
        question: "What happens to the magnetic field when current direction is reversed?",
        options: ["Disappears", "Doubles", "Direction reverses", "Becomes weaker"],
        correctAnswer: 2,
        explanation: "When current direction is reversed, the magnetic field direction also reverses.",
        difficulty: "medium",
        subject: "physics",
        topic: "Magnetism",
        points: 30,
      },
    ],
  },
  {
    id: "physics-hard-2",
    title: "Modern Physics",
    subject: "physics",
    difficulty: "hard",
    timeLimit: 30,
    passingScore: 80,
    totalPoints: 200,
    description: "Quantum mechanics and relativity concepts",
    questions: [
      {
        id: "p5q1",
        question: "According to Einstein's mass-energy equation, what is the energy equivalent of 1 kg of mass?",
        options: ["3×10⁸ J", "9×10¹⁶ J", "3×10¹⁶ J", "9×10⁸ J"],
        correctAnswer: 1,
        explanation: "E = mc² = 1 kg × (3×10⁸ m/s)² = 9×10¹⁶ J",
        difficulty: "hard",
        subject: "physics",
        topic: "Relativity",
        points: 40,
      },
      {
        id: "p5q2",
        question: "What is the de Broglie wavelength associated with matter?",
        options: ["λ = h/p", "λ = hf", "λ = mc²", "λ = E/h"],
        correctAnswer: 0,
        explanation: "de Broglie wavelength λ = h/p, where h is Planck's constant and p is momentum.",
        difficulty: "hard",
        subject: "physics",
        topic: "Quantum Mechanics",
        points: 40,
      },
      {
        id: "p5q3",
        question: "In the photoelectric effect, the kinetic energy of emitted electrons depends on:",
        options: ["Intensity of light", "Frequency of light", "Duration of exposure", "Temperature"],
        correctAnswer: 1,
        explanation: "KE = hf - φ, where f is frequency. Kinetic energy depends on frequency, not intensity.",
        difficulty: "hard",
        subject: "physics",
        topic: "Photoelectric Effect",
        points: 40,
      },
      {
        id: "p5q4",
        question: "What does Heisenberg's uncertainty principle state?",
        options: [
          "Energy is quantized",
          "Position and momentum cannot both be precisely known",
          "Light has wave-particle duality",
          "Time is relative",
        ],
        correctAnswer: 1,
        explanation:
          "Heisenberg's principle: Δx·Δp ≥ ℏ/2, meaning position and momentum cannot both be precisely determined.",
        difficulty: "hard",
        subject: "physics",
        topic: "Quantum Mechanics",
        points: 40,
      },
      {
        id: "p5q5",
        question: "At what speed does time dilation become significant?",
        options: ["10% of light speed", "50% of light speed", "Speeds comparable to light", "Any speed"],
        correctAnswer: 2,
        explanation:
          "Time dilation becomes significant at speeds comparable to the speed of light (relativistic speeds).",
        difficulty: "hard",
        subject: "physics",
        topic: "Relativity",
        points: 40,
      },
    ],
  },

  // Chemistry Quizzes
  {
    id: "chemistry-easy-1",
    title: "Basic Atomic Structure",
    subject: "chemistry",
    difficulty: "easy",
    timeLimit: 15,
    passingScore: 70,
    totalPoints: 100,
    description: "Introduction to atoms, elements, and the periodic table",
    questions: [
      {
        id: "c1q1",
        question: "What is the smallest unit of an element?",
        options: ["Molecule", "Atom", "Ion", "Compound"],
        correctAnswer: 1,
        explanation: "An atom is the smallest unit of an element that retains its chemical properties.",
        difficulty: "easy",
        subject: "chemistry",
        topic: "Atomic Structure",
        points: 20,
      },
      {
        id: "c1q2",
        question: "How many protons does a carbon atom have?",
        options: ["4", "6", "8", "12"],
        correctAnswer: 1,
        explanation: "Carbon has atomic number 6, which means it has 6 protons.",
        difficulty: "easy",
        subject: "chemistry",
        topic: "Periodic Table",
        points: 20,
      },
      {
        id: "c1q3",
        question: "What charge does an electron have?",
        options: ["Positive", "Negative", "Neutral", "Variable"],
        correctAnswer: 1,
        explanation: "Electrons have a negative charge (-1).",
        difficulty: "easy",
        subject: "chemistry",
        topic: "Atomic Structure",
        points: 20,
      },
      {
        id: "c1q4",
        question: "Which particle is found in the nucleus of an atom?",
        options: ["Electron", "Proton", "Neutron", "Both proton and neutron"],
        correctAnswer: 3,
        explanation: "The nucleus contains both protons and neutrons.",
        difficulty: "easy",
        subject: "chemistry",
        topic: "Atomic Structure",
        points: 20,
      },
      {
        id: "c1q5",
        question: "What is the chemical symbol for oxygen?",
        options: ["O", "Ox", "Og", "Om"],
        correctAnswer: 0,
        explanation: "The chemical symbol for oxygen is O.",
        difficulty: "easy",
        subject: "chemistry",
        topic: "Chemical Symbols",
        points: 20,
      },
    ],
  },
  {
    id: "chemistry-medium-1",
    title: "Chemical Bonding",
    subject: "chemistry",
    difficulty: "medium",
    timeLimit: 20,
    passingScore: 75,
    totalPoints: 150,
    description: "Understanding ionic and covalent bonds",
    questions: [
      {
        id: "c2q1",
        question: "What type of bond forms between sodium and chlorine in NaCl?",
        options: ["Covalent", "Ionic", "Metallic", "Hydrogen"],
        correctAnswer: 1,
        explanation: "Sodium (metal) and chlorine (non-metal) form an ionic bond through electron transfer.",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Chemical Bonding",
        points: 30,
      },
      {
        id: "c2q2",
        question: "How many electrons does oxygen need to complete its outer shell?",
        options: ["1", "2", "6", "8"],
        correctAnswer: 1,
        explanation: "Oxygen has 6 valence electrons and needs 2 more to complete its octet.",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Electron Configuration",
        points: 30,
      },
      {
        id: "c2q3",
        question: "What is the molecular formula for water?",
        options: ["HO", "H₂O", "H₃O", "HO₂"],
        correctAnswer: 1,
        explanation: "Water has the molecular formula H₂O (2 hydrogen atoms, 1 oxygen atom).",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Molecular Formulas",
        points: 30,
      },
      {
        id: "c2q4",
        question: "Which type of bond involves sharing electrons?",
        options: ["Ionic", "Covalent", "Metallic", "Van der Waals"],
        correctAnswer: 1,
        explanation: "Covalent bonds form when atoms share electrons.",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Chemical Bonding",
        points: 30,
      },
      {
        id: "c2q5",
        question: "What is the charge on a calcium ion (Ca²⁺)?",
        options: ["+1", "+2", "-1", "-2"],
        correctAnswer: 1,
        explanation: "Ca²⁺ indicates calcium has lost 2 electrons, giving it a +2 charge.",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Ions",
        points: 30,
      },
    ],
  },
  {
    id: "chemistry-hard-1",
    title: "Chemical Equilibrium",
    subject: "chemistry",
    difficulty: "hard",
    timeLimit: 25,
    passingScore: 80,
    totalPoints: 200,
    description: "Advanced concepts in chemical equilibrium and Le Chatelier's principle",
    questions: [
      {
        id: "c3q1",
        question:
          "For the reaction A + B ⇌ C + D, if [A] = 2M, [B] = 3M, [C] = 1M, [D] = 1M, and Kc = 0.5, which direction will the reaction proceed?",
        options: ["Forward", "Reverse", "At equilibrium", "Cannot determine"],
        correctAnswer: 1,
        explanation:
          "Qc = [C][D]/[A][B] = (1)(1)/(2)(3) = 1/6 ≈ 0.17. Since Qc < Kc, reaction proceeds forward. Wait, let me recalculate: Qc = 1/6 = 0.17, Kc = 0.5, so Qc < Kc means forward. Actually, let me be more careful: if Qc < Kc, reaction goes forward to reach equilibrium.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Chemical Equilibrium",
        points: 40,
      },
      {
        id: "c3q2",
        question:
          "According to Le Chatelier's principle, what happens when pressure is increased in the reaction N₂ + 3H₂ ⇌ 2NH₃?",
        options: ["Shifts left", "Shifts right", "No change", "Reaction stops"],
        correctAnswer: 1,
        explanation:
          "Increasing pressure shifts equilibrium toward the side with fewer gas molecules (4 moles → 2 moles), so it shifts right.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Le Chatelier's Principle",
        points: 40,
      },
      {
        id: "c3q3",
        question: "What is the relationship between Kc and Kp for the reaction 2SO₂ + O₂ ⇌ 2SO₃?",
        options: ["Kp = Kc", "Kp = Kc(RT)", "Kp = Kc(RT)⁻¹", "Kp = Kc(RT)²"],
        correctAnswer: 2,
        explanation: "Kp = Kc(RT)^Δn, where Δn = 2 - (2+1) = -1, so Kp = Kc(RT)⁻¹.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Equilibrium Constants",
        points: 40,
      },
      {
        id: "c3q4",
        question: "In a buffer solution, what happens when a small amount of acid is added?",
        options: [
          "pH drops significantly",
          "pH rises significantly",
          "pH remains nearly constant",
          "Buffer is destroyed",
        ],
        correctAnswer: 2,
        explanation: "A buffer resists pH changes by neutralizing small amounts of added acid or base.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Buffers",
        points: 40,
      },
      {
        id: "c3q5",
        question: "What is the pH of a 0.01 M HCl solution?",
        options: ["1", "2", "12", "13"],
        correctAnswer: 1,
        explanation: "HCl is a strong acid, so [H⁺] = 0.01 M. pH = -log(0.01) = -log(10⁻²) = 2.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "pH and Acids",
        points: 40,
      },
    ],
  },
  {
    id: "chemistry-medium-2",
    title: "Organic Chemistry Basics",
    subject: "chemistry",
    difficulty: "medium",
    timeLimit: 20,
    passingScore: 75,
    totalPoints: 150,
    description: "Introduction to organic compounds and functional groups",
    questions: [
      {
        id: "c4q1",
        question: "What is the general formula for alkanes?",
        options: ["CₙH₂ₙ", "CₙH₂ₙ₊₂", "CₙH₂ₙ₋₂", "CₙHₙ"],
        correctAnswer: 1,
        explanation: "Alkanes are saturated hydrocarbons with the general formula CₙH₂ₙ₊₂.",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Organic Chemistry",
        points: 30,
      },
      {
        id: "c4q2",
        question: "Which functional group is present in alcohols?",
        options: ["-COOH", "-OH", "-CHO", "-CO-"],
        correctAnswer: 1,
        explanation: "Alcohols contain the hydroxyl functional group (-OH).",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Functional Groups",
        points: 30,
      },
      {
        id: "c4q3",
        question: "What type of reaction occurs when ethene (C₂H₄) reacts with hydrogen?",
        options: ["Substitution", "Addition", "Elimination", "Condensation"],
        correctAnswer: 1,
        explanation: "Ethene undergoes addition reaction with hydrogen to form ethane.",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Organic Reactions",
        points: 30,
      },
      {
        id: "c4q4",
        question: "How many carbon atoms are in propane?",
        options: ["2", "3", "4", "5"],
        correctAnswer: 1,
        explanation: "Propane (C₃H₈) has 3 carbon atoms.",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Hydrocarbons",
        points: 30,
      },
      {
        id: "c4q5",
        question: "What is the IUPAC name for CH₃CH₂OH?",
        options: ["Methanol", "Ethanol", "Propanol", "Butanol"],
        correctAnswer: 1,
        explanation: "CH₃CH₂OH is ethanol (2-carbon alcohol).",
        difficulty: "medium",
        subject: "chemistry",
        topic: "Nomenclature",
        points: 30,
      },
    ],
  },
  {
    id: "chemistry-hard-2",
    title: "Thermodynamics and Kinetics",
    subject: "chemistry",
    difficulty: "hard",
    timeLimit: 30,
    passingScore: 80,
    totalPoints: 200,
    description: "Advanced concepts in chemical thermodynamics and reaction kinetics",
    questions: [
      {
        id: "c5q1",
        question: "For a spontaneous process at constant temperature and pressure, what must be true about ΔG?",
        options: ["ΔG > 0", "ΔG < 0", "ΔG = 0", "ΔG is undefined"],
        correctAnswer: 1,
        explanation: "For a spontaneous process, the Gibbs free energy change (ΔG) must be negative.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Thermodynamics",
        points: 40,
      },
      {
        id: "c5q2",
        question: "What is the relationship between rate constant k and temperature according to Arrhenius equation?",
        options: [
          "k decreases with temperature",
          "k increases exponentially with temperature",
          "k is independent of temperature",
          "k varies linearly with temperature",
        ],
        correctAnswer: 1,
        explanation:
          "According to Arrhenius equation k = Ae^(-Ea/RT), rate constant increases exponentially with temperature.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Chemical Kinetics",
        points: 40,
      },
      {
        id: "c5q3",
        question:
          "What is the order of reaction if doubling the concentration of reactant A doubles the reaction rate?",
        options: ["Zero order", "First order", "Second order", "Third order"],
        correctAnswer: 1,
        explanation: "If rate doubles when concentration doubles, the reaction is first order in A.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Reaction Order",
        points: 40,
      },
      {
        id: "c5q4",
        question: "What does a catalyst do to the activation energy of a reaction?",
        options: ["Increases it", "Decreases it", "No effect", "Makes it zero"],
        correctAnswer: 1,
        explanation: "A catalyst provides an alternative pathway with lower activation energy.",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Catalysis",
        points: 40,
      },
      {
        id: "c5q5",
        question: "For the reaction ΔH = -100 kJ/mol, ΔS = -200 J/mol·K at 298K, what is ΔG?",
        options: ["-40.4 kJ/mol", "-159.6 kJ/mol", "-40400 J/mol", "Cannot determine"],
        correctAnswer: 0,
        explanation: "ΔG = ΔH - TΔS = -100 kJ/mol - (298K)(-0.2 kJ/mol·K) = -100 + 59.6 = -40.4 kJ/mol",
        difficulty: "hard",
        subject: "chemistry",
        topic: "Gibbs Free Energy",
        points: 40,
      },
    ],
  },

  // Biology Quizzes
  {
    id: "biology-easy-1",
    title: "Cell Structure and Function",
    subject: "biology",
    difficulty: "easy",
    timeLimit: 15,
    passingScore: 70,
    totalPoints: 100,
    description: "Basic concepts of cell biology and organelles",
    questions: [
      {
        id: "b1q1",
        question: "What is the basic unit of life?",
        options: ["Tissue", "Organ", "Cell", "Organism"],
        correctAnswer: 2,
        explanation: "The cell is the basic structural and functional unit of all living organisms.",
        difficulty: "easy",
        subject: "biology",
        topic: "Cell Biology",
        points: 20,
      },
      {
        id: "b1q2",
        question: "Which organelle is known as the 'powerhouse of the cell'?",
        options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi apparatus"],
        correctAnswer: 1,
        explanation:
          "Mitochondria produce ATP through cellular respiration, earning the nickname 'powerhouse of the cell'.",
        difficulty: "easy",
        subject: "biology",
        topic: "Cell Organelles",
        points: 20,
      },
      {
        id: "b1q3",
        question: "What controls what enters and leaves the cell?",
        options: ["Cell wall", "Cell membrane", "Nucleus", "Cytoplasm"],
        correctAnswer: 1,
        explanation: "The cell membrane is selectively permeable and controls the passage of substances.",
        difficulty: "easy",
        subject: "biology",
        topic: "Cell Membrane",
        points: 20,
      },
      {
        id: "b1q4",
        question: "Where is genetic material stored in a cell?",
        options: ["Mitochondria", "Ribosome", "Nucleus", "Vacuole"],
        correctAnswer: 2,
        explanation: "The nucleus contains the cell's DNA and controls cellular activities.",
        difficulty: "easy",
        subject: "biology",
        topic: "Cell Nucleus",
        points: 20,
      },
      {
        id: "b1q5",
        question: "What do ribosomes make?",
        options: ["DNA", "Proteins", "Lipids", "Carbohydrates"],
        correctAnswer: 1,
        explanation: "Ribosomes are the sites of protein synthesis in cells.",
        difficulty: "easy",
        subject: "biology",
        topic: "Protein Synthesis",
        points: 20,
      },
    ],
  },
  {
    id: "biology-medium-1",
    title: "Genetics and Heredity",
    subject: "biology",
    difficulty: "medium",
    timeLimit: 20,
    passingScore: 75,
    totalPoints: 150,
    description: "Understanding inheritance patterns and genetic principles",
    questions: [
      {
        id: "b2q1",
        question:
          "In a cross between two heterozygous parents (Aa × Aa), what is the probability of offspring being homozygous recessive?",
        options: ["0%", "25%", "50%", "75%"],
        correctAnswer: 1,
        explanation: "In Aa × Aa cross: AA (25%), Aa (50%), aa (25%). Homozygous recessive (aa) = 25%.",
        difficulty: "medium",
        subject: "biology",
        topic: "Mendelian Genetics",
        points: 30,
      },
      {
        id: "b2q2",
        question: "What is the complementary DNA strand for ATCG?",
        options: ["TAGC", "UAGC", "CGAT", "GCTA"],
        correctAnswer: 0,
        explanation: "DNA base pairing: A-T and C-G. So ATCG pairs with TAGC.",
        difficulty: "medium",
        subject: "biology",
        topic: "DNA Structure",
        points: 30,
      },
      {
        id: "b2q3",
        question: "During which phase of mitosis do chromosomes align at the cell's equator?",
        options: ["Prophase", "Metaphase", "Anaphase", "Telophase"],
        correctAnswer: 1,
        explanation: "During metaphase, chromosomes align at the metaphase plate (cell's equator).",
        difficulty: "medium",
        subject: "biology",
        topic: "Cell Division",
        points: 30,
      },
      {
        id: "b2q4",
        question: "What is a mutation?",
        options: ["Normal cell division", "Change in DNA sequence", "Protein synthesis", "Energy production"],
        correctAnswer: 1,
        explanation: "A mutation is any change in the DNA sequence that can affect gene function.",
        difficulty: "medium",
        subject: "biology",
        topic: "Mutations",
        points: 30,
      },
      {
        id: "b2q5",
        question: "How many chromosomes do humans have in their somatic cells?",
        options: ["23", "46", "92", "44"],
        correctAnswer: 1,
        explanation: "Human somatic cells are diploid with 46 chromosomes (23 pairs).",
        difficulty: "medium",
        subject: "biology",
        topic: "Human Genetics",
        points: 30,
      },
    ],
  },
  {
    id: "biology-hard-1",
    title: "Molecular Biology",
    subject: "biology",
    difficulty: "hard",
    timeLimit: 25,
    passingScore: 80,
    totalPoints: 200,
    description: "Advanced concepts in gene expression and molecular processes",
    questions: [
      {
        id: "b3q1",
        question: "What is the role of RNA polymerase II in eukaryotes?",
        options: ["Transcribes rRNA", "Transcribes mRNA", "Transcribes tRNA", "Replicates DNA"],
        correctAnswer: 1,
        explanation: "RNA polymerase II transcribes protein-coding genes to produce mRNA in eukaryotes.",
        difficulty: "hard",
        subject: "biology",
        topic: "Transcription",
        points: 40,
      },
      {
        id: "b3q2",
        question: "During translation, what brings amino acids to the ribosome?",
        options: ["mRNA", "rRNA", "tRNA", "DNA"],
        correctAnswer: 2,
        explanation: "tRNA (transfer RNA) carries specific amino acids to the ribosome during translation.",
        difficulty: "hard",
        subject: "biology",
        topic: "Translation",
        points: 40,
      },
      {
        id: "b3q3",
        question: "What is the function of the 5' cap and 3' poly-A tail in mRNA?",
        options: ["Start translation", "Protect from degradation", "Bind to DNA", "Form secondary structure"],
        correctAnswer: 1,
        explanation: "The 5' cap and 3' poly-A tail protect mRNA from degradation and aid in translation.",
        difficulty: "hard",
        subject: "biology",
        topic: "mRNA Processing",
        points: 40,
      },
      {
        id: "b3q4",
        question: "What is alternative splicing?",
        options: ["DNA repair mechanism", "Different ways to join exons", "Chromosome segregation", "Protein folding"],
        correctAnswer: 1,
        explanation:
          "Alternative splicing allows different combinations of exons to create multiple proteins from one gene.",
        difficulty: "hard",
        subject: "biology",
        topic: "Gene Expression",
        points: 40,
      },
      {
        id: "b3q5",
        question: "What is the central dogma of molecular biology?",
        options: ["DNA → RNA → Protein", "Protein → RNA → DNA", "RNA → DNA → Protein", "DNA → Protein → RNA"],
        correctAnswer: 0,
        explanation: "The central dogma describes information flow: DNA → RNA → Protein.",
        difficulty: "hard",
        subject: "biology",
        topic: "Central Dogma",
        points: 40,
      },
    ],
  },
  {
    id: "biology-medium-2",
    title: "Ecology and Environment",
    subject: "biology",
    difficulty: "medium",
    timeLimit: 20,
    passingScore: 75,
    totalPoints: 150,
    description: "Understanding ecosystems and environmental interactions",
    questions: [
      {
        id: "b4q1",
        question: "What is the primary source of energy for most ecosystems?",
        options: ["Wind", "Sunlight", "Water", "Soil"],
        correctAnswer: 1,
        explanation: "Sunlight is the primary energy source for most ecosystems through photosynthesis.",
        difficulty: "medium",
        subject: "biology",
        topic: "Ecosystems",
        points: 30,
      },
      {
        id: "b4q2",
        question: "Which organisms are at the base of most food chains?",
        options: ["Herbivores", "Carnivores", "Producers", "Decomposers"],
        correctAnswer: 2,
        explanation:
          "Producers (plants and other autotrophs) form the base of food chains by converting sunlight to energy.",
        difficulty: "medium",
        subject: "biology",
        topic: "Food Chains",
        points: 30,
      },
      {
        id: "b4q3",
        question: "What is biodiversity?",
        options: ["Number of ecosystems", "Variety of life forms", "Population size", "Genetic mutations"],
        correctAnswer: 1,
        explanation: "Biodiversity refers to the variety of life forms in an ecosystem or on Earth.",
        difficulty: "medium",
        subject: "biology",
        topic: "Biodiversity",
        points: 30,
      },
      {
        id: "b4q4",
        question: "What is the greenhouse effect?",
        options: ["Cooling of Earth", "Trapping of heat in atmosphere", "Ozone depletion", "Acid rain formation"],
        correctAnswer: 1,
        explanation: "The greenhouse effect is the trapping of heat in Earth's atmosphere by greenhouse gases.",
        difficulty: "medium",
        subject: "biology",
        topic: "Climate Change",
        points: 30,
      },
      {
        id: "b4q5",
        question: "What is a keystone species?",
        options: [
          "Most abundant species",
          "Species with disproportionate ecosystem impact",
          "Largest species",
          "First species in food chain",
        ],
        correctAnswer: 1,
        explanation: "A keystone species has a disproportionately large impact on ecosystem structure and function.",
        difficulty: "medium",
        subject: "biology",
        topic: "Ecology",
        points: 30,
      },
    ],
  },
  {
    id: "biology-hard-2",
    title: "Evolution and Natural Selection",
    subject: "biology",
    difficulty: "hard",
    timeLimit: 30,
    passingScore: 80,
    totalPoints: 200,
    description: "Advanced concepts in evolutionary biology and mechanisms of evolution",
    questions: [
      {
        id: "b5q1",
        question: "What is the Hardy-Weinberg principle used to calculate?",
        options: ["Mutation rates", "Allele frequencies", "Population growth", "Species diversity"],
        correctAnswer: 1,
        explanation:
          "Hardy-Weinberg principle calculates allele and genotype frequencies in populations under equilibrium.",
        difficulty: "hard",
        subject: "biology",
        topic: "Population Genetics",
        points: 40,
      },
      {
        id: "b5q2",
        question: "Which type of natural selection reduces variation in a population?",
        options: ["Directional", "Stabilizing", "Disruptive", "Sexual"],
        correctAnswer: 1,
        explanation: "Stabilizing selection favors intermediate phenotypes, reducing variation around the mean.",
        difficulty: "hard",
        subject: "biology",
        topic: "Natural Selection",
        points: 40,
      },
      {
        id: "b5q3",
        question: "What is genetic drift?",
        options: [
          "Gene flow between populations",
          "Random changes in allele frequencies",
          "Mutation accumulation",
          "Natural selection",
        ],
        correctAnswer: 1,
        explanation: "Genetic drift is the random change in allele frequencies, especially in small populations.",
        difficulty: "hard",
        subject: "biology",
        topic: "Genetic Drift",
        points: 40,
      },
      {
        id: "b5q4",
        question: "What evidence supports the theory of evolution?",
        options: [
          "Fossil record only",
          "DNA similarities only",
          "Multiple lines of evidence",
          "Anatomical structures only",
        ],
        correctAnswer: 2,
        explanation:
          "Evolution is supported by multiple lines of evidence: fossils, DNA, anatomy, biogeography, and more.",
        difficulty: "hard",
        subject: "biology",
        topic: "Evidence for Evolution",
        points: 40,
      },
      {
        id: "b5q5",
        question: "What is speciation?",
        options: [
          "Extinction of species",
          "Formation of new species",
          "Migration of species",
          "Adaptation to environment",
        ],
        correctAnswer: 1,
        explanation: "Speciation is the evolutionary process by which new species arise from existing ones.",
        difficulty: "hard",
        subject: "biology",
        topic: "Speciation",
        points: 40,
      },
    ],
  },

  // Mathematics Quizzes
  {
    id: "mathematics-easy-1",
    title: "Basic Algebra",
    subject: "mathematics",
    difficulty: "easy",
    timeLimit: 15,
    passingScore: 70,
    totalPoints: 100,
    description: "Introduction to algebraic expressions and simple equations",
    questions: [
      {
        id: "m1q1",
        question: "Solve for x: 2x + 5 = 13",
        options: ["x = 4", "x = 6", "x = 8", "x = 9"],
        correctAnswer: 0,
        explanation: "2x + 5 = 13, so 2x = 8, therefore x = 4.",
        difficulty: "easy",
        subject: "mathematics",
        topic: "Linear Equations",
        points: 20,
      },
      {
        id: "m1q2",
        question: "What is 3² + 4²?",
        options: ["25", "49", "7", "12"],
        correctAnswer: 0,
        explanation: "3² + 4² = 9 + 16 = 25.",
        difficulty: "easy",
        subject: "mathematics",
        topic: "Exponents",
        points: 20,
      },
      {
        id: "m1q3",
        question: "Simplify: 3x + 2x",
        options: ["5x", "6x", "5x²", "6x²"],
        correctAnswer: 0,
        explanation: "3x + 2x = (3 + 2)x = 5x.",
        difficulty: "easy",
        subject: "mathematics",
        topic: "Combining Like Terms",
        points: 20,
      },
      {
        id: "m1q4",
        question: "What is the value of x if x/4 = 3?",
        options: ["12", "7", "1", "4/3"],
        correctAnswer: 0,
        explanation: "x/4 = 3, so x = 3 × 4 = 12.",
        difficulty: "easy",
        subject: "mathematics",
        topic: "Solving Equations",
        points: 20,
      },
      {
        id: "m1q5",
        question: "Expand: 2(x + 3)",
        options: ["2x + 3", "2x + 6", "x + 6", "2x + 5"],
        correctAnswer: 1,
        explanation: "2(x + 3) = 2x + 2(3) = 2x + 6.",
        difficulty: "easy",
        subject: "mathematics",
        topic: "Distributive Property",
        points: 20,
      },
    ],
  },
  {
    id: "mathematics-medium-1",
    title: "Quadratic Equations",
    subject: "mathematics",
    difficulty: "medium",
    timeLimit: 20,
    passingScore: 75,
    totalPoints: 150,
    description: "Solving quadratic equations and understanding parabolas",
    questions: [
      {
        id: "m2q1",
        question: "Solve: x² - 5x + 6 = 0",
        options: ["x = 2, 3", "x = 1, 6", "x = -2, -3", "x = 2, -3"],
        correctAnswer: 0,
        explanation: "x² - 5x + 6 = (x - 2)(x - 3) = 0, so x = 2 or x = 3.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Quadratic Equations",
        points: 30,
      },
      {
        id: "m2q2",
        question: "What is the discriminant of x² + 4x + 4 = 0?",
        options: ["0", "16", "8", "-16"],
        correctAnswer: 0,
        explanation: "Discriminant = b² - 4ac = 4² - 4(1)(4) = 16 - 16 = 0.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Discriminant",
        points: 30,
      },
      {
        id: "m2q3",
        question: "What is the vertex of the parabola y = x² - 4x + 3?",
        options: ["(2, -1)", "(2, 1)", "(-2, -1)", "(-2, 1)"],
        correctAnswer: 0,
        explanation: "Vertex x-coordinate: -b/2a = -(-4)/2(1) = 2. y = 2² - 4(2) + 3 = -1. Vertex: (2, -1).",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Parabolas",
        points: 30,
      },
      {
        id: "m2q4",
        question: "Using the quadratic formula, what are the solutions to x² + 2x - 3 = 0?",
        options: ["x = 1, -3", "x = -1, 3", "x = 1, 3", "x = -1, -3"],
        correctAnswer: 0,
        explanation: "x = (-2 ± √(4 + 12))/2 = (-2 ± 4)/2. So x = 1 or x = -3.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Quadratic Formula",
        points: 30,
      },
      {
        id: "m2q5",
        question: "How many real solutions does x² + x + 1 = 0 have?",
        options: ["0", "1", "2", "3"],
        correctAnswer: 0,
        explanation: "Discriminant = 1² - 4(1)(1) = -3 < 0, so there are no real solutions.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Real Solutions",
        points: 30,
      },
    ],
  },
  {
    id: "mathematics-hard-1",
    title: "Calculus Fundamentals",
    subject: "mathematics",
    difficulty: "hard",
    timeLimit: 25,
    passingScore: 80,
    totalPoints: 200,
    description: "Introduction to limits, derivatives, and basic integration",
    questions: [
      {
        id: "m3q1",
        question: "What is the limit of (x² - 4)/(x - 2) as x approaches 2?",
        options: ["0", "2", "4", "undefined"],
        correctAnswer: 2,
        explanation: "(x² - 4)/(x - 2) = (x + 2)(x - 2)/(x - 2) = x + 2. As x → 2, limit = 4.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Limits",
        points: 40,
      },
      {
        id: "m3q2",
        question: "What is the derivative of f(x) = 3x² + 2x - 1?",
        options: ["6x + 2", "6x - 1", "3x + 2", "6x² + 2x"],
        correctAnswer: 0,
        explanation: "f'(x) = d/dx(3x²) + d/dx(2x) - d/dx(1) = 6x + 2 - 0 = 6x + 2.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Derivatives",
        points: 40,
      },
      {
        id: "m3q3",
        question: "What is ∫(2x + 3)dx?",
        options: ["x² + 3x + C", "2x² + 3x + C", "x² + 3x", "2x + 3x + C"],
        correctAnswer: 0,
        explanation: "∫(2x + 3)dx = ∫2x dx + ∫3 dx = x² + 3x + C.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Integration",
        points: 40,
      },
      {
        id: "m3q4",
        question: "At what point does f(x) = x² - 4x + 3 have a minimum?",
        options: ["x = 2", "x = -2", "x = 1", "x = 3"],
        correctAnswer: 0,
        explanation: "f'(x) = 2x - 4 = 0 when x = 2. Since f''(x) = 2 > 0, x = 2 is a minimum.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Optimization",
        points: 40,
      },
      {
        id: "m3q5",
        question: "What is the derivative of sin(x)?",
        options: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"],
        correctAnswer: 0,
        explanation: "The derivative of sin(x) is cos(x).",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Trigonometric Derivatives",
        points: 40,
      },
    ],
  },
  {
    id: "mathematics-medium-2",
    title: "Geometry and Trigonometry",
    subject: "mathematics",
    difficulty: "medium",
    timeLimit: 20,
    passingScore: 75,
    totalPoints: 150,
    description: "Understanding geometric shapes and trigonometric functions",
    questions: [
      {
        id: "m4q1",
        question: "What is the area of a circle with radius 5?",
        options: ["25π", "10π", "5π", "50π"],
        correctAnswer: 0,
        explanation: "Area = πr² = π(5)² = 25π.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Circle Area",
        points: 30,
      },
      {
        id: "m4q2",
        question: "In a right triangle, if sin(θ) = 3/5, what is cos(θ)?",
        options: ["4/5", "3/4", "5/4", "5/3"],
        correctAnswer: 0,
        explanation: "Using Pythagorean identity: sin²(θ) + cos²(θ) = 1. If sin(θ) = 3/5, then cos(θ) = 4/5.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Trigonometry",
        points: 30,
      },
      {
        id: "m4q3",
        question: "What is the volume of a cube with side length 4?",
        options: ["16", "64", "12", "48"],
        correctAnswer: 1,
        explanation: "Volume of cube = side³ = 4³ = 64.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Volume",
        points: 30,
      },
      {
        id: "m4q4",
        question: "What is the sum of interior angles of a pentagon?",
        options: ["540°", "720°", "360°", "180°"],
        correctAnswer: 0,
        explanation: "Sum of interior angles = (n-2) × 180° = (5-2) × 180° = 540°.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Polygons",
        points: 30,
      },
      {
        id: "m4q5",
        question: "What is tan(45°)?",
        options: ["1", "√2", "1/2", "√3"],
        correctAnswer: 0,
        explanation: "tan(45°) = sin(45°)/cos(45°) = (√2/2)/(√2/2) = 1.",
        difficulty: "medium",
        subject: "mathematics",
        topic: "Special Angles",
        points: 30,
      },
    ],
  },
  {
    id: "mathematics-hard-2",
    title: "Advanced Functions",
    subject: "mathematics",
    difficulty: "hard",
    timeLimit: 30,
    passingScore: 80,
    totalPoints: 200,
    description: "Complex functions, logarithms, and exponential functions",
    questions: [
      {
        id: "m5q1",
        question: "What is log₂(8)?",
        options: ["2", "3", "4", "8"],
        correctAnswer: 1,
        explanation: "log₂(8) = log₂(2³) = 3.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Logarithms",
        points: 40,
      },
      {
        id: "m5q2",
        question: "If f(x) = eˣ, what is f'(x)?",
        options: ["eˣ", "xeˣ⁻¹", "ln(x)", "1/x"],
        correctAnswer: 0,
        explanation: "The derivative of eˣ is eˣ.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Exponential Functions",
        points: 40,
      },
      {
        id: "m5q3",
        question: "What is the domain of f(x) = √(x - 3)?",
        options: ["x ≥ 3", "x > 3", "x ≤ 3", "All real numbers"],
        correctAnswer: 0,
        explanation: "For √(x - 3) to be real, we need x - 3 ≥ 0, so x ≥ 3.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Domain and Range",
        points: 40,
      },
      {
        id: "m5q4",
        question: "What is the inverse of f(x) = 2x + 1?",
        options: ["f⁻¹(x) = (x-1)/2", "f⁻¹(x) = (x+1)/2", "f⁻¹(x) = 2x - 1", "f⁻¹(x) = x/2 - 1"],
        correctAnswer: 0,
        explanation: "Let y = 2x + 1, solve for x: x = (y-1)/2. So f⁻¹(x) = (x-1)/2.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Inverse Functions",
        points: 40,
      },
      {
        id: "m5q5",
        question: "What is lim(x→∞) (1 + 1/x)ˣ?",
        options: ["1", "e", "∞", "0"],
        correctAnswer: 1,
        explanation: "This is the definition of e: lim(x→∞) (1 + 1/x)ˣ = e.",
        difficulty: "hard",
        subject: "mathematics",
        topic: "Limits",
        points: 40,
      },
    ],
  },
]

export function getQuizzesBySubject(subject: "physics" | "chemistry" | "biology" | "mathematics"): Quiz[] {
  return quizData.filter((quiz) => quiz.subject === subject)
}

export function getQuizById(id: string): Quiz | undefined {
  return quizData.find((quiz) => quiz.id === id)
}

export function getQuizzesByDifficulty(difficulty: "easy" | "medium" | "hard"): Quiz[] {
  return quizData.filter((quiz) => quiz.difficulty === difficulty)
}

export function getQuizBySubjectAndDifficulty(
  subject: "physics" | "chemistry" | "biology" | "mathematics",
  difficulty: "easy" | "medium" | "hard",
): Quiz | undefined {
  return quizData.find((quiz) => quiz.subject === subject && quiz.difficulty === difficulty)
}

export function getRecommendedQuizForLesson(lessonSubject: string, lessonDifficulty: string): Quiz | undefined {
  const subject = lessonSubject.toLowerCase() as "physics" | "chemistry" | "biology" | "mathematics"

  // Map lesson difficulty to quiz difficulty
  let quizDifficulty: "easy" | "medium" | "hard" = "easy"
  if (lessonDifficulty === "intermediate") quizDifficulty = "medium"
  if (lessonDifficulty === "advanced") quizDifficulty = "hard"

  // Try to find exact match first
  let quiz = getQuizBySubjectAndDifficulty(subject, quizDifficulty)

  // If no exact match, get any quiz from the subject
  if (!quiz) {
    const subjectQuizzes = getQuizzesBySubject(subject)
    quiz = subjectQuizzes[0]
  }

  return quiz
}
